{
 "title": "Globus Endpoint Stats",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "SHOW TAG VALUES WITH KEY = \"endpoint\" WHERE time > now() - 7d"
   }
  ]
 },
 "panels": [
  {
   "title": "Globus Transfer Map",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select files,latitude,longitude from transfer where $timeFilter and endpoint =~ /$endpoint$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(bytes) from transfer where $timeFilter and endpoint =~ /$endpoint$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Files Transferred",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(files) from transfer where $timeFilter and endpoint =~ /$endpoint$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Buffer Sizes Chosen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select buffer from transfer where $timeFilter and endpoint =~ /$endpoint$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Data",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(bytes) from transfer where $timeFilter and endpoint =~ /$endpoint$/ group by time(5m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Transferred by User",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(bytes) from transfer where $timeFilter  and endpoint =~ /$endpoint$/ group by \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Files Transferred by User",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(files) from transfer where $timeFilter  and endpoint =~ /$endpoint$/ group by \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Transferred by Action",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(bytes) from transfer where $timeFilter  and endpoint =~ /$endpoint$/ group by \"type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Transferred by Source/Dest Organization",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "$tag_src_dest_org",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(bytes),sum(files) from transfer where $timeFilter  and endpoint =~ /$endpoint$/ group by \"src_dest_org\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Files transferred per Endpoint Host",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 25 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(files) from transfer where $timeFilter  and endpoint =~ /$endpoint$/ GROUP BY time($__interval),host fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}